name: transfluent.github.io
description: Transfluent API Documentation
author:
  name: Transfluent Coders
  email: coders@transfluent.com
rouge: true
exclude: ['node_modules', '.gitignore', 'bower_components', 'bower.json', 'gulpfile.js', 'README.md', 'config.rb', 'package.json', 'Gemfil*']
timezone: Europe/Helsinki
permalink: /:title
markdown: kramdown
port: 4001
