- Name: callback_url
  Description: Callback URL which will be called once translation is completed. Please see:- Callbacks
  Optional: false

- Name: comment
  Description: 
  Optional: false
  
- Name: content
  Description: 
  Optional: false
  
- Name: customer_id
  Description: Customer id. Optionally you can call the method without providing customer id but you MUST provide a valid authentication token.
  Optional: false

- Name: email
  Description: A valid email address is required in order to create a new account
  Optional: false
  
- Name: format [=UTF-8]
  Description: 
  Optional: false

- Name: group_id
  Description: Group id for texts (alphanumeric string, recommended max length 32 characters). If provided, all text ids in group are visible only in the group (e.g. text ids won't collide between groups).
  Optional: true

- Name: identifier
  Description: 
  Optional: false

- Name: invalidate_translations [=1]
  Description: A boolean value (1/0;on/off) which controls if translations are trashed or not. E.g. if you make a spelling error correction to the original text, you probably don't want to trash the translations and re-translate the text. Also if you save previously made translation to our system using this method, it's really important to set invalidate_translations off!
  Optional: true

- Name: is_draft
  Description: A boolean value (1/0;on/off) which controls if translations is a draft or not. Draft translations are checked by a translator when translation request is placed
  Optional: true

- Name: language
  Description: Language id (int). The human language text provided is written in. E.g. 1 = English (GB), 11 = Finnish. Please refer to /languages/-method for full list of language ids.
  Optional: false

- Name: level [=3]
  Description: 
  Optional: false

- Name: name
  Description: 
  Optional: false
  
- Name: notify [=1]
  Description: Send account password and welcome email to the customer via email
  Optional: true

- Name: password
  Description: Passowrd for user account
  Optional: false

- Name: return_other_levels
  Description: 
  Optional: false

- Name: save_only_data
  Description: 
  Optional: false

- Name: source_language
  Description: 
  Optional: false

- Name: target_languages
  Description: 
  Optional: false
  
- Name: terms
  Description: Has customer accepted Terms of Service? If so, only valid value is "ok"
  Optional: false

- Name: text
  Description: either source text to translate or previously made translation you want to save into our system. May contain HTML or any other markup.
  Optional: false

- Name: text_id
  Description: <code>text_id</code> is a unique key for your content. It must be an alphanumeric string, maximum length is 64 characters. If <code>group_id</code> is provided, it will be prefixed with the group id, i.e. each group has namespace of its own for text ids.
  Optional: false

- Name: token
  Description: Authentication token which can be acquired with valid transfluent.com account credentials using authenticate-method For details, please see:- Authenticate
  Optional: false

- Name: type
  Description: 
  Optional: false

